// System — whether this run is worth trusting.
//
// The dashboard is generated by a pipeline that partially fails all the time:
// a blocked exchange, a rate-limited Screener, a delisted symbol. Coverage
// numbers are how a reader tells "nothing happened" from "we could not look",
// and those two look identical everywhere else in the product.

import { el, mount } from "../core/dom.js";
import { dataTable, panel } from "./table.js";

/**
 * Derived channels worth stating a count for, every run.
 *
 * A channel can die completely and leave no mark anywhere else in the product:
 * its view simply renders an empty table, which looks identical to a quiet
 * day. That is exactly what happened to the Screener peer radar — competitor
 * discovery, candidate screening and industry share all returned nothing for
 * several consecutive runs and nothing on screen said so.
 *
 * These are counts, not alarms. Several of them are legitimately zero on a
 * normal day, and a red badge on a quiet Tuesday teaches the reader to ignore
 * the panel. The number is the signal; the reader knows which ones should
 * never be zero.
 */
const CHANNELS = [
  ["peer_competitors", "Competitor radar", "Screener industry peers"],
  ["candidate_screen", "Candidate screen", "peers that cleared the gates"],
  ["industry_share", "Industry share", "share within a Screener industry"],
  ["market_share", "Peer market share", "share among our own holdings"],
  ["market_events", "Market events", "classified this run"],
  ["input_cost_shock", "Input cost shocks", "sectors with a material move"],
  ["sector_growth", "Sector growth", "sectors ranked"],
  ["institutional_activity", "Institutional activity", "block deals and flows"],
];

/** Absent (never ran) and empty (ran, found nothing) are different states. */
function channelRows(briefing) {
  return CHANNELS.map(([key, label, note]) => {
    const value = briefing?.[key];
    const present = briefing && key in briefing;
    const count =
      value && typeof value === "object" ? Object.keys(value).length : null;
    return {
      label,
      note,
      state: !present ? "did not run" : count === 0 ? "nothing" : String(count),
      _count: present ? (count ?? 0) : -1,
    };
  });
}

export async function render(container, { payload, route }) {
  const b = payload?.briefing || {};
  const watchlist = payload?.watchlist || {};
  const holdings = Object.values(watchlist).flat().filter((s) => s && s.ticker);

  const priced = holdings.filter((s) => s.price).length;
  const screened = holdings.filter((s) => s.screener && Object.keys(s.screener).length).length;
  const withDelivery = holdings.filter(
    (s) => s.screener?.deliv_pct !== undefined && s.screener?.deliv_pct !== null,
  ).length;

  const coverage = b.coverage_count || {};
  const covered = Object.keys(coverage).length;

  const rows = [
    { field: "Live price", got: priced, of: holdings.length },
    { field: "Screener fundamentals", got: screened, of: holdings.length },
    { field: "Delivery percentage", got: withDelivery, of: holdings.length },
    { field: "News coverage", got: covered, of: holdings.length },
  ];

  mount(
    container,
    el(
      "header",
      { class: "view-head" },
      el("h2", { class: "view-title" }, "Run health"),
      el("p", { class: "view-sub" }, `Generated ${payload?.last_updated || "—"}`),
    ),
    panel(
      "Coverage",
      "A field missing for most holdings means the source refused us, not that " +
        "the answer is zero. The two are different and only this view separates them.",
      dataTable(
        rows,
        [
          { key: "field", label: "Field" },
          { key: "got", label: "Holdings", numeric: true, render: (r) => `${r.got} / ${r.of}` },
          {
            key: "share",
            label: "Coverage",
            numeric: true,
            render: (r) => (r.of ? `${Math.round((100 * r.got) / r.of)}%` : "—"),
          },
        ],
        { empty: "No watchlist loaded." },
      ),
    ),
    panel(
      "Derived channels",
      "What each analysis step produced this run. A channel can fail entirely " +
        "and still leave its view looking like a quiet day — this is where the " +
        "difference shows. “Did not run” and “nothing” are " +
        "not the same: the first never executed, the second executed and found " +
        "no rows.",
      dataTable(
        channelRows(b),
        [
          { key: "label", label: "Channel" },
          { key: "note", label: "What it counts", sortable: false },
          {
            key: "_count",
            label: "This run",
            numeric: true,
            render: (r) =>
              el(
                "span",
                { class: r._count === 0 ? "cell-bad" : r._count < 0 ? "band-churn" : "" },
                r.state,
              ),
          },
        ],
        { view: "system", route, empty: "No briefing loaded." },
      ),
    ),
    panel(
      "Payload",
      "Sidecars are fetched on demand rather than shipped with the page.",
      el(
        "ul",
        { class: "plain-list" },
        el("li", {}, `Briefing keys: ${Object.keys(b).length}`),
        el(
          "li",
          {},
          `Sidecar keys: ${
            Object.entries(b)
              .filter(([, v]) => v && typeof v === "object" && v.sidecar)
              .map(([k]) => k)
              .join(", ") || "none"
          }`,
        ),
      ),
    ),
  );
}
