// System — whether this run is worth trusting.
//
// The dashboard is generated by a pipeline that partially fails all the time:
// a blocked exchange, a rate-limited Screener, a delisted symbol. Coverage
// numbers are how a reader tells "nothing happened" from "we could not look",
// and those two look identical everywhere else in the product.

import { el, mount } from "../core/dom.js";
import { dataTable, panel } from "./table.js";

export async function render(container, { payload }) {
  const b = payload?.briefing || {};
  const watchlist = payload?.watchlist || {};
  const holdings = Object.values(watchlist).flat().filter((s) => s && s.ticker);

  const priced = holdings.filter((s) => s.price).length;
  const screened = holdings.filter((s) => s.screener && Object.keys(s.screener).length).length;
  const withDelivery = holdings.filter(
    (s) => s.screener?.deliv_pct !== undefined && s.screener?.deliv_pct !== null,
  ).length;

  const coverage = b.coverage_count || {};
  const covered = Object.keys(coverage).length;

  const rows = [
    { field: "Live price", got: priced, of: holdings.length },
    { field: "Screener fundamentals", got: screened, of: holdings.length },
    { field: "Delivery percentage", got: withDelivery, of: holdings.length },
    { field: "News coverage", got: covered, of: holdings.length },
  ];

  mount(
    container,
    el(
      "header",
      { class: "view-head" },
      el("h2", { class: "view-title" }, "Run health"),
      el("p", { class: "view-sub" }, `Generated ${payload?.last_updated || "—"}`),
    ),
    panel(
      "Coverage",
      "A field missing for most holdings means the source refused us, not that " +
        "the answer is zero. The two are different and only this view separates them.",
      dataTable(
        rows,
        [
          { key: "field", label: "Field" },
          { key: "got", label: "Holdings", numeric: true, render: (r) => `${r.got} / ${r.of}` },
          {
            key: "share",
            label: "Coverage",
            numeric: true,
            render: (r) => (r.of ? `${Math.round((100 * r.got) / r.of)}%` : "—"),
          },
        ],
        { empty: "No watchlist loaded." },
      ),
    ),
    panel(
      "Payload",
      "Sidecars are fetched on demand rather than shipped with the page.",
      el(
        "ul",
        { class: "plain-list" },
        el("li", {}, `Briefing keys: ${Object.keys(b).length}`),
        el(
          "li",
          {},
          `Sidecar keys: ${
            Object.entries(b)
              .filter(([, v]) => v && typeof v === "object" && v.sidecar)
              .map(([k]) => k)
              .join(", ") || "none"
          }`,
        ),
      ),
    ),
  );
}
