// System — whether this run is worth trusting.
//
// The dashboard is generated by a pipeline that partially fails all the time:
// a blocked exchange, a rate-limited Screener, a delisted symbol. Coverage
// numbers are how a reader tells "nothing happened" from "we could not look",
// and those two look identical everywhere else in the product.

import { el, mount } from "../core/dom.js";
import { dataTable, panel } from "./table.js";

/**
 * Derived channels worth stating a count for, every run.
 *
 * A channel can die completely and leave no mark anywhere else in the product:
 * its view simply renders an empty table, which looks identical to a quiet
 * day. That is exactly what happened to the Screener peer radar — competitor
 * discovery, candidate screening and industry share all returned nothing for
 * several consecutive runs and nothing on screen said so.
 *
 * These are counts, not alarms. Several of them are legitimately zero on a
 * normal day, and a red badge on a quiet Tuesday teaches the reader to ignore
 * the panel. The number is the signal; the reader knows which ones should
 * never be zero.
 */
// [payload key, label, what the number counts, expected, count?]
//
// `expected` says whether zero is a problem. Several of these are legitimately
// zero on a normal day — no peer clears the screen, nothing is classified on a
// quiet Sunday — and painting those red teaches the reader to ignore the panel,
// which costs exactly the signal it exists to carry.
//
// `count` is supplied where the payload key is a wrapper rather than the
// collection itself. input_cost_shock is {sectors, inputs, unmeasured}, so
// counting its keys reported "3" on every run regardless of what happened.
const CHANNELS = [
  ["peer_competitors", "Competitor radar", "sectors with peers found", true],
  ["candidate_screen", "Candidate screen", "sectors with a candidate", false],
  ["industry_share", "Industry share", "sectors measured", true],
  ["market_share", "Peer market share", "sectors measured", true],
  ["market_events", "Market events", "classified this run", false],
  [
    "input_cost_shock",
    "Input cost shocks",
    "sectors with a material move",
    false,
    (v) => Object.keys(v?.sectors || {}).length,
  ],
  ["sector_growth", "Sector growth", "sectors ranked", true],
  ["read_throughs", "Read-throughs", "second-order flags", false],
  ["institutional_activity", "Institutional activity", "block deals and flows", false],
];

const DID_NOT_RUN = -1;

/** Absent (never ran) and empty (ran, found nothing) are different states. */
function channelRows(briefing) {
  return CHANNELS.map(([key, label, note, expected, count]) => {
    const value = briefing?.[key];
    const present = Boolean(briefing) && key in briefing;
    let n = null;
    if (present && value && typeof value === "object") {
      n = count ? count(value) : Object.keys(value).length;
    }
    return {
      label,
      note,
      expected: Boolean(expected),
      state: !present ? "did not run" : n === 0 ? "nothing" : String(n ?? 0),
      _count: present ? (n ?? 0) : DID_NOT_RUN,
    };
  });
}

/**
 * Tone for a count.
 *
 * "Did not run" is always wrong — the step should have executed. Zero is only
 * wrong for channels that should always produce something; for the rest it is
 * an ordinary quiet day and gets no colour at all.
 */
function countTone(row) {
  if (row._count === DID_NOT_RUN) return "band-churn";
  if (row._count === 0 && row.expected) return "cell-bad";
  return "";
}

export async function render(container, { payload, route }) {
  const b = payload?.briefing || {};
  const watchlist = payload?.watchlist || {};
  const holdings = Object.values(watchlist).flat().filter((s) => s && s.ticker);

  const priced = holdings.filter((s) => s.price).length;
  const screened = holdings.filter((s) => s.screener && Object.keys(s.screener).length).length;
  const withDelivery = holdings.filter(
    (s) => s.screener?.deliv_pct !== undefined && s.screener?.deliv_pct !== null,
  ).length;

  const coverage = b.coverage_count || {};
  const covered = Object.keys(coverage).length;

  const rows = [
    { field: "Live price", got: priced, of: holdings.length },
    { field: "Screener fundamentals", got: screened, of: holdings.length },
    { field: "Delivery percentage", got: withDelivery, of: holdings.length },
    { field: "News coverage", got: covered, of: holdings.length },
  ];

  mount(
    container,
    el(
      "header",
      { class: "view-head" },
      el("h2", { class: "view-title" }, "Run health"),
      el("p", { class: "view-sub" }, `Generated ${payload?.last_updated || "—"}`),
    ),
    panel(
      "Coverage",
      "A field missing for most holdings means the source refused us, not that " +
        "the answer is zero. The two are different and only this view separates them.",
      dataTable(
        rows,
        [
          { key: "field", label: "Field" },
          { key: "got", label: "Holdings", numeric: true, render: (r) => `${r.got} / ${r.of}` },
          {
            key: "share",
            label: "Coverage",
            numeric: true,
            render: (r) => (r.of ? `${Math.round((100 * r.got) / r.of)}%` : "—"),
          },
        ],
        { empty: "No watchlist loaded." },
      ),
    ),
    panel(
      "Derived channels",
      "What each analysis step produced this run. A channel can fail entirely " +
        "and still leave its view looking like a quiet day — this is where the " +
        "difference shows. “Did not run” and “nothing” are " +
        "not the same: the first never executed, the second executed and found " +
        "no rows. Only a zero that should never be zero is marked; several of " +
        "these are legitimately empty on a quiet day.",
      dataTable(
        channelRows(b),
        [
          { key: "label", label: "Channel" },
          { key: "note", label: "What it counts", sortable: false },
          {
            key: "_count",
            label: "This run",
            numeric: true,
            render: (r) => el("span", { class: countTone(r) }, r.state),
          },
        ],
        { view: "system", route, empty: "No briefing loaded." },
      ),
    ),
    panel(
      "Payload",
      "Sidecars are fetched on demand rather than shipped with the page.",
      el(
        "ul",
        { class: "plain-list" },
        el("li", {}, `Briefing keys: ${Object.keys(b).length}`),
        el(
          "li",
          {},
          `Sidecar keys: ${
            Object.entries(b)
              .filter(([, v]) => v && typeof v === "object" && v.sidecar)
              .map(([k]) => k)
              .join(", ") || "none"
          }`,
        ),
      ),
    ),
  );
}
