// The app shell: nav, theme, and which view the route names.

import { useState, useEffect, useCallback } from "preact/hooks";
import { href } from "./core/router.js";
import { useRoute, usePayload } from "./hooks.js";
import { EmptyState } from "./components/ui.jsx";

import { Overview } from "./views/Overview.jsx";
import { Holdings } from "./views/Holdings.jsx";
import { Valuation } from "./views/Valuation.jsx";
import { Risk } from "./views/Risk.jsx";
import { Flow } from "./views/Flow.jsx";
import { Network } from "./views/Network.jsx";
import { System } from "./views/System.jsx";

// Seven views for sixteen tabs, grouped by the question a reader is asking
// rather than by which scraper produced the data.
//
// tests/test_email_sections.py parses this object to check that every
// fragment the daily email links to still names a real view — three of them
// silently stopped resolving when the tabs were consolidated, which is a dead
// link in every briefing. Keep the shape parseable.
const VIEWS = {
  overview: { label: "Overview", component: Overview },
  holdings: { label: "Holdings", component: Holdings },
  valuation: { label: "Valuation", component: Valuation },
  risk: { label: "Risk", component: Risk },
  flow: { label: "Flow", component: Flow },
  network: { label: "Network", component: Network },
  system: { label: "Run health", component: System },
};

function useTheme() {
  const [theme, setTheme] = useState(() => {
    try {
      return localStorage.getItem("theme") || "";
    } catch {
      return ""; // private mode, or site data blocked
    }
  });
  useEffect(() => {
    document.documentElement.dataset.theme = theme;
  }, [theme]);
  const toggle = useCallback(() => {
    setTheme((current) => {
      const next = current === "dark" ? "light" : "dark";
      try {
        localStorage.setItem("theme", next);
      } catch {
        /* nothing to do; the toggle still works for this session */
      }
      return next;
    });
  }, []);
  return [theme, toggle];
}

export function App() {
  const route = useRoute();
  const payload = usePayload();
  const [, toggleTheme] = useTheme();

  const key = VIEWS[route.view] ? route.view : "overview";
  const View = VIEWS[key].component;

  return (
    <>
      <header class="app-head">
        <div class="brand">
          <span class="brand-mark" aria-hidden="true">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round">
              <rect x="3" y="3" width="18" height="18" rx="4.5" />
              <line x1="8" y1="16.5" x2="8" y2="12.5" />
              <line x1="12" y1="16.5" x2="12" y2="7.5" />
              <line x1="16" y1="16.5" x2="16" y2="10.5" />
            </svg>
          </span>
          <span class="brand-name">India Policy Tracker</span>
        </div>
        <button class="theme-toggle" type="button" onClick={toggleTheme} aria-label="Switch theme">
          ◐
        </button>
      </header>

      <nav class="main-nav" role="tablist">
        {Object.entries(VIEWS).map(([k, { label }]) => (
          <a
            key={k}
            class={`nav-item${k === key ? " nav-active" : ""}`}
            href={href(k)}
            role="tab"
            aria-selected={k === key ? "true" : "false"}
          >
            {label}
          </a>
        ))}
      </nav>

      <main id="view" class="view" tabIndex={-1}>
        {payload.status === "loading" && <p class="loading">Loading…</p>}
        {payload.status === "error" && (
          <EmptyState
            message="Could not load dashboard_data.json."
            detail={String(payload.error?.message || "")}
          />
        )}
        {payload.status === "ready" && <View payload={payload.data} route={route} />}
      </main>

      <footer class="app-foot">
        <span>
          Generated by an automated pipeline. Figures are as published by the sources named;
          absence of a figure means it could not be read, not zero.
        </span>
      </footer>
    </>
  );
}
